import type { RenderedStateName } from "./verify-report.js";

/**
 * The preview.html artifact: the verifier's rendered state strings, wrapped in
 * a single self-contained page a reviewer can open straight from the out
 * directory. The acceptance run hand-built exactly this page to review the
 * first live draft; emitting it standard makes "look at the four states" a
 * one-double-click step instead of a scaffolding exercise.
 *
 * Self-containment is a hard property: the host stylesheet is inlined in a
 * <style> block, the states are inline HTML, and there is no script and no
 * external request of any kind — the page must be reviewable offline and
 * attach-to-a-PR safe.
 */

export const PREVIEW_STATE_ORDER: readonly RenderedStateName[] = [
  "ready",
  "empty",
  "error",
  "truncated",
];

export interface RenderPreviewHtmlOptions {
  componentId: string;
  /** The host stylesheet text (the corpus's concatenation), inlined verbatim. */
  stylesheetText: string;
  /** Rendered HTML per state. A state that failed to render may be absent. */
  states: Partial<Record<RenderedStateName, string>>;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/**
 * A literal `</style>` inside the inlined stylesheet would terminate the
 * style block and dump the rest of the CSS into the body. `<\/style>` is
 * byte-identical CSS (the backslash escapes a character that needs none) but
 * can never close the tag.
 */
function escapeForStyleBlock(css: string): string {
  return css.replace(/<\//g, "<\\/");
}

/** The preview's own chrome, prefixed so it cannot collide with host classes. */
const PREVIEW_CHROME_CSS = `
body { margin: 0; }
.iv-preview-header {
  font-family: system-ui, sans-serif;
  padding: 16px 24px;
  border-bottom: 1px solid #ccc;
}
.iv-preview-header h1 { font-size: 18px; font-weight: 600; margin: 0; }
.iv-preview-header p { font-size: 13px; color: #555; margin: 4px 0 0; }
.iv-preview-states {
  display: flex;
  flex-wrap: wrap;
  gap: 16px;
  align-items: flex-start;
  padding: 24px;
}
.iv-preview-state {
  flex: 1 1 300px;
  min-width: 260px;
  border: 1px dashed #999;
  border-radius: 4px;
  padding: 12px;
}
.iv-preview-state-label {
  font-family: system-ui, sans-serif;
  font-size: 12px;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.06em;
  color: #555;
  margin: 0 0 12px;
}
.iv-preview-state-missing {
  font-family: system-ui, sans-serif;
  font-size: 13px;
  color: #a33;
  margin: 0;
}
`;

export function renderPreviewHtml(options: RenderPreviewHtmlOptions): string {
  const title = `${escapeHtml(options.componentId)} — rendered states`;
  const sections = PREVIEW_STATE_ORDER.map((state) => {
    const html = options.states[state];
    const body =
      html === undefined
        ? `<p class="iv-preview-state-missing">This state did not render — see verification-report.md.</p>`
        : html;
    return [
      `      <section class="iv-preview-state">`,
      `        <h2 class="iv-preview-state-label">${escapeHtml(state)}</h2>`,
      `        <div class="iv-preview-state-body">${body}</div>`,
      `      </section>`,
    ].join("\n");
  }).join("\n");
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${title}</title>
    <style>${PREVIEW_CHROME_CSS}</style>
    <style>
/* Host stylesheet, inlined by @renderyes/generate. */
${escapeForStyleBlock(options.stylesheetText)}
    </style>
  </head>
  <body>
    <header class="iv-preview-header">
      <h1>${title}</h1>
      <p>Generated by @renderyes/generate — self-contained, no scripts, no external requests.</p>
    </header>
    <main class="iv-preview-states">
${sections}
    </main>
  </body>
</html>
`;
}
