import assert from "node:assert/strict";
import test from "node:test";
import { execFileSync } from "node:child_process";
import { cpSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import {
  buildRegistrationPatch,
  createScriptedGenerateProvider,
  deriveTwinDefinition,
  findRegistrationFiles,
  generateComponent,
  GenerateRefusalError,
  loadDataContractFromExport,
  renderTwinModule,
  unifiedDiffForFile,
  writeArtifacts,
} from "../dist/index.js";
import {
  buildReviewExportBundle,
  flawedEnvelope,
  goodEnvelope,
  LISTED_HOST_DIR,
} from "./fixture.mjs";

test("unifiedDiffForFile produces correct hunks for multiple insertions", () => {
  const oldText = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"].join("\n") + "\n";
  const diff = unifiedDiffForFile("file.txt", oldText, [
    { afterLine: 1, lines: ["one", "two"] },
    { afterLine: 9, lines: ["nine"] },
  ]);
  assert.match(diff, /^--- a\/file\.txt\n\+\+\+ b\/file\.txt\n/);
  assert.match(diff, /@@ -1,4 \+1,6 @@/);
  assert.match(diff, /@@ -7,4 \+9,5 @@/);
  assert.match(diff, / a\n\+one\n\+two\n b\n/);
});

test("the registration patch inserts registration on both sides and git-applies cleanly", () => {
  const registration = findRegistrationFiles(LISTED_HOST_DIR);
  assert.equal(registration.clientPath, "components.jsx");
  assert.equal(registration.serverPath, "server-defs.mjs");

  const { patch, notes } = buildRegistrationPatch({
    registration,
    spec: goodEnvelope().spec,
    viewFileName: "PantryShoppingList.view.jsx",
    twinFileName: "PantryShoppingList.component.mjs",
  });
  assert.equal(notes.length, 0);
  assert.match(patch, /\+import { ingestViews } from "@renderyes\/react";/);
  assert.match(
    patch,
    /\+import \* as pantryShoppingListModule from ".\/PantryShoppingList\.view\.jsx";/,
  );
  assert.match(patch, /\+const \[pantryShoppingListRegistration\] = ingestViews\(\{/);
  assert.match(patch, /\+ {2}pantryShoppingListRegistration,/);
  assert.match(
    patch,
    /\+import { pantryShoppingListDefinition } from ".\/PantryShoppingList\.component\.mjs";/,
  );
  assert.match(patch, /\+ {2}pantryShoppingListDefinition,/);

  // The proof: git apply accepts it against a copy of the host.
  const workDir = mkdtempSync(join(tmpdir(), "iv-generate-apply-"));
  cpSync(LISTED_HOST_DIR, workDir, { recursive: true });
  writeFileSync(join(workDir, "registration.patch"), patch);
  execFileSync("git", ["init", "--quiet"], { cwd: workDir });
  execFileSync("git", ["apply", "--check", "registration.patch"], { cwd: workDir });
  execFileSync("git", ["apply", "registration.patch"], { cwd: workDir });
  const patched = readFileSync(join(workDir, "components.jsx"), "utf8");
  assert.ok(patched.includes("pantryShoppingListRegistration,"));
  const patchedServer = readFileSync(join(workDir, "server-defs.mjs"), "utf8");
  assert.ok(patchedServer.includes("pantryShoppingListDefinition,"));
});

test("the emitted twin module evaluates to exactly the derived definition", async () => {
  const spec = goodEnvelope().spec;
  const source = renderTwinModule(spec);
  assert.match(source, /GENERATED by @renderyes\/generate/);

  // Import the literal source the artifact would contain, resolving the bare
  // site-sdk specifier the way a host's node_modules would.
  const resolved = import.meta.resolve("@renderyes/site-sdk");
  const dir = mkdtempSync(join(tmpdir(), "iv-generate-twin-"));
  const file = join(dir, "twin.mjs");
  writeFileSync(
    file,
    source.replace('"@renderyes/site-sdk"', JSON.stringify(resolved)),
  );
  const module = await import(pathToFileURL(file).href);
  const evaluated = module.pantryShoppingListDefinition;
  const derived = deriveTwinDefinition(spec);

  const projection = (definition) =>
    JSON.parse(
      JSON.stringify({
        id: definition.id,
        version: definition.version,
        description: definition.description,
        renderer: definition.renderer,
        dataSlots: definition.dataSlots,
        propsSchema: definition.props.jsonSchema,
      }),
    );
  assert.deepEqual(projection(evaluated), projection(derived));
});

test("listed-convention generation emits the twin and the patch", async () => {
  const provider = createScriptedGenerateProvider([goodEnvelope()]);
  const contract = loadDataContractFromExport(buildReviewExportBundle());
  const result = await generateComponent({
    contract,
    capabilityId: "pantry.items.list",
    provider,
    hostDir: LISTED_HOST_DIR,
    componentId: "PantryShoppingList",
  });
  assert.equal(result.convention, "listed");
  assert.deepEqual(
    result.artifacts.map((artifact) => artifact.name),
    [
      "PantryShoppingList.view.jsx",
      "PantryShoppingList.component.mjs",
      "registration.patch",
      "verification-report.md",
      "preview.html",
      "sample-rows.json",
    ],
  );
});

test("writeArtifacts refuses to overwrite unless told to", async () => {
  const provider = createScriptedGenerateProvider([goodEnvelope()]);
  const contract = loadDataContractFromExport(buildReviewExportBundle());
  const result = await generateComponent({
    contract,
    capabilityId: "pantry.items.list",
    provider,
    hostDir: LISTED_HOST_DIR,
    componentId: "PantryShoppingList",
  });

  const outDir = mkdtempSync(join(tmpdir(), "iv-generate-out-"));
  writeArtifacts(result.artifacts, outDir, false);
  assert.throws(
    () => writeArtifacts(result.artifacts, outDir, false),
    GenerateRefusalError,
  );
  // With overwrite it succeeds.
  writeArtifacts(result.artifacts, outDir, true);
  assert.ok(readFileSync(join(outDir, "PantryShoppingList.view.jsx"), "utf8").length > 0);
});

test("a failing final draft still carries FAIL markings into the report artifact", async () => {
  const provider = createScriptedGenerateProvider([
    flawedEnvelope(),
    flawedEnvelope(),
    flawedEnvelope(),
  ]);
  const contract = loadDataContractFromExport(buildReviewExportBundle());
  const result = await generateComponent({
    contract,
    capabilityId: "pantry.items.list",
    provider,
    hostDir: LISTED_HOST_DIR,
    componentId: "PantryShoppingList",
  });
  const report = result.artifacts.find(
    (artifact) => artifact.name === "verification-report.md",
  );
  assert.match(report.content, /render-smoke \| FAIL/);
});

/**
 * A `.view.tsx` is a contract plus a component, not a registration.
 *
 * The scaffold's `views/index.js` collects registrations, and the publish step
 * refuses a bare spec — correctly, since a spec carries no renderer. Both
 * shapes are supported and `ingestViews` is what converts one to the other,
 * a fact that lived only in the refusal, which a host reads after the mistake.
 */
test("the report says what turns a generated view into a registration", async () => {
  const { buildArtifacts } = await import("../dist/emit.js");
  const { goodEnvelope, buildReviewExportBundle } = await import("./fixture.mjs");
  const { loadDataContractFromExport, sliceCapability } = await import("../dist/index.js");
  const contract = loadDataContractFromExport(buildReviewExportBundle());
  const slice = sliceCapability(contract, "pantry.items.list");

  for (const convention of ["folder", "listed"]) {
    const artifacts = buildArtifacts({
      envelope: goodEnvelope(),
      slice,
      convention,
      fileExtension: ".jsx",
      report: { checks: [], notes: [] },
      rounds: 1,
      styleSystem: "plain",
      stylesheetText: "",
      sampleRows: [],
    });
    const report = artifacts.find((file) => file.name === "verification-report.md");
    assert.ok(report, `${convention}: no report emitted`);
    assert.match(report.content, /ingestViews/, `${convention}: report never names the bridge`);
  }
});
