import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import Ajv2020 from "ajv/dist/2020.js";
import { describe, expect, it } from "vitest";
import packageJson from "../package.json" with { type: "json" };

/**
 * The contracts, shipped as JSON Schema, and actually describing the artifacts.
 *
 * A generated schema can be wrong in two directions and neither shows up by
 * looking at it: too loose, and it certifies a file the compile will refuse;
 * too strict, and it rejects a file the compile accepts. So these validate real
 * artifacts produced by the real binary, in both directions — a genuine file
 * passes, and a plausible-looking extra key fails, because these are strict
 * objects and "additionalProperties" is exactly what a reader inferring the
 * shape from an example gets backwards.
 *
 * Draft 2020-12, matching what the rest of this package already emits and
 * consumes (`ajv/dist/2020.js`, see validate-data.ts).
 */

const CLI = fileURLToPath(new URL("../bin/catalog.mjs", import.meta.url));
const schemaPath = (name: string) =>
  fileURLToPath(new URL(`../schemas/${name}.schema.json`, import.meta.url));

const SHIPPED = ["graphql-decisions", "capability-catalog", "review-export"];

function ajv() {
  const Ctor = (Ajv2020 as unknown as { default?: typeof Ajv2020 }).default ?? Ajv2020;
  // `strict: false` only silences unknown-format notes (`uri`); it does not
  // relax any assertion these tests rely on.
  return new Ctor({ strict: false, allErrors: true });
}

function readSchema(name: string) {
  const path = schemaPath(name);
  if (!existsSync(path)) {
    throw new Error(
      `${path} is missing. The schemas are generated by the build — run \`npm run build\`.`,
    );
  }
  return JSON.parse(readFileSync(path, "utf8"));
}

describe("shipped JSON Schemas", () => {
  it("are listed in files, so they reach a tarball", () => {
    // The gap this catches is the one that already shipped once with LICENSE:
    // a file that exists in the repository and in no install.
    expect(packageJson.files).toContain("schemas");
    expect(packageJson.exports["./schemas/*"]).toBe("./schemas/*");
    // Generated by the build, so a schema cannot drift from its Zod definition.
    expect(packageJson.scripts.build).toContain("emit-json-schemas");
  });

  it("are valid, self-describing JSON Schema", () => {
    for (const name of SHIPPED) {
      const schema = readSchema(name);
      expect(() => ajv().compile(schema), name).not.toThrow();
      // Titles and descriptions are the whole point for a reader who found the
      // file without finding the docs.
      expect(schema.title, name).toBeTruthy();
      expect(schema.description, name).toBeTruthy();
    }
  });

  it("accept what the binary actually produces, and refuse what it would not", () => {
    const dir = fileURLToPath(new URL(".", import.meta.url));
    const workspaceDir = execFileSync(
      process.execPath,
      ["-e", "process.stdout.write(require('node:fs').mkdtempSync(require('node:path').join(require('node:os').tmpdir(),'iv-schemas-')))"],
      { encoding: "utf8", cwd: dir },
    );
    const file = (name: string) => `${workspaceDir}/${name}`;
    execFileSync(process.execPath, ["-e",
      `require('node:fs').writeFileSync(${JSON.stringify(file("schema.graphql"))}, ${JSON.stringify(`
        type Query { "List orders." orders(first: Int, after: String): OrderConnection }
        type OrderConnection { edges: [OrderEdge!]!  pageInfo: PageInfo! }
        type OrderEdge { cursor: String!  node: Order! }
        type PageInfo { hasNextPage: Boolean!  endCursor: String }
        type Order { id: ID!  number: String! }
      `)})`]);

    const run = (args: string[]) =>
      execFileSync(process.execPath, [CLI, ...args], { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });

    run(["inventory", "--schema", file("schema.graphql"), "--catalog-id", "shop",
         "--queries", "orders", "--out", file("inventory.json")]);
    run(["candidate", "--inventory", file("inventory.json"), "--approve-all-discovered",
         "--out", file("decisions.json")]);
    run(["compile", "--schema", file("schema.graphql"), "--inventory", file("inventory.json"),
         "--decisions", file("decisions.json"), "--endpoint", "https://api.example/graphql",
         "--out", file("catalog.json")]);

    const validator = ajv();
    const decisions = JSON.parse(readFileSync(file("decisions.json"), "utf8"));
    const validateDecisions = validator.compile(readSchema("graphql-decisions"));
    expect(validateDecisions(decisions), JSON.stringify(validateDecisions.errors)).toBe(true);

    // `$schema` is emitted into the file, and the file is a strictObject — so
    // the schema has to admit its own pointer or pointing an editor at it makes
    // the file invalid, which would defeat shipping it.
    expect(decisions.$schema).toContain("schemas/graphql-decisions.schema.json");

    // The other direction. A reader who inferred this format from an example
    // would assume extra keys are tolerated; the compile refuses them, and so
    // must the schema, or CI passes on a file that cannot publish.
    expect(validateDecisions({ ...decisions, approvedFields: ["id"] })).toBe(false);
    expect(validateDecisions({ ...decisions, schemaVersion: "2.0" })).toBe(false);

    const compiled = JSON.parse(readFileSync(file("catalog.json"), "utf8"));
    const validateCatalog = validator.compile(readSchema("capability-catalog"));
    expect(validateCatalog(compiled.catalog), JSON.stringify(validateCatalog.errors)).toBe(true);
  });
});
