/**
 * Every guide in `docs/` must appear in `sidebars.ts`.
 *
 * Docusaurus catches a *renamed* guide on its own — the sidebar names an id
 * that no longer resolves and the build fails. It does not catch an *added*
 * one: the page is generated and routable, and simply never appears in the
 * navigation. No warning, exit code 0. A guide nobody can find from the site
 * is the same failure as a guide that was never published, and it is the
 * quieter of the two.
 *
 * The ordinary alternative — an autogenerated sidebar — is not available here.
 * It needs a `sidebar_position` in each document's frontmatter, and these files
 * are copied verbatim into the published tarballs by
 * `packages/server/scripts/copy-host-docs.mjs`, so that frontmatter would greet
 * every consumer who opens `node_modules/@renderyes/server/docs/QUICKSTART.md`.
 * The sidebar is written by hand for that reason, and this is what keeps a
 * hand-written list honest.
 *
 * Runs from `prebuild`, so it gates the Pages deploy rather than being a check
 * someone has to remember.
 */
import { readFile, readdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const docsDir = resolve(here, "../../docs");
const sidebarPath = resolve(here, "../sidebars.ts");
const configPath = resolve(here, "../docusaurus.config.ts");

/**
 * A guide the site deliberately does not publish is not a guide missing from
 * the sidebar. The config's `exclude` is the one place that decision is made,
 * so it is read from there rather than restated here — two lists would drift,
 * and the failure would be this check passing while the page still builds.
 */
const config = await readFile(configPath, "utf8");
const excluded = new Set(
  [...(/\bexclude:\s*\[([^\]]*)\]/.exec(config)?.[1] ?? "").matchAll(
    /["']([^"']+)["']/g,
  )].map((match) => match[1].replace(/\.md$/, "")),
);

const present = (await readdir(docsDir))
  .filter((name) => name.endsWith(".md"))
  .map((name) => name.replace(/\.md$/, ""))
  .filter((id) => !excluded.has(id))
  .sort();

// The ids as written in the sidebar. Matching the source text rather than
// importing it keeps this free of a TypeScript loader, and the file is a plain
// literal list by design.
const sidebar = await readFile(sidebarPath, "utf8");
const listed = new Set(
  [...sidebar.matchAll(/\bid:\s*["']([^"']+)["']/g)].map((match) => match[1]),
);

const missing = present.filter((id) => !listed.has(id));
const phantom = [...listed].filter((id) => !present.includes(id)).sort();

if (missing.length === 0 && phantom.length === 0) {
  const aside =
    excluded.size > 0 ? ` (${[...excluded].sort().join(", ")} excluded)` : "";
  console.log(`sidebar: ${present.length} guides, all listed${aside}`);
  process.exit(0);
}

if (missing.length > 0) {
  console.error(
    "These guides exist in docs/ and are in no sidebar category, so the site\n" +
      "would build them as pages nothing links to:\n",
  );
  for (const id of missing) console.error(`  docs/${id}.md`);
  console.error("\nAdd each to a category in website/sidebars.ts.");
}

if (phantom.length > 0) {
  console.error(
    "\nThe sidebar names guides that docs/ does not have — renamed or deleted:\n",
  );
  for (const id of phantom) console.error(`  ${id}`);
  console.error("\nUpdate website/sidebars.ts to match.");
}

process.exit(1);
